version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.dockerfile
        volumes:
            - ./app:/app
            - ./custom.php.ini:/usr/local/etc/php/conf.d/php.ini
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'qwerty'
            #MYSQL_USER: 'root'
            #MYSQL_PASSWORD: 'secret'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8080:80
        environment:
            PMA_HOST: mysql
volumes:
    mysqldata: {}
